artifact_location: /home/elisey/cv/Real-time_Number_Plate_Recognition/notebooks/runs/mlflow/0
creation_time: 1732399734104
experiment_id: '0'
last_update_time: 1732399734104
lifecycle_stage: active
name: Default
