artifact_location: /home/elisey/cv/Real-time_Number_Plate_Recognition/notebooks/runs/mlflow/651226193700422918
creation_time: 1732399734118
experiment_id: '651226193700422918'
last_update_time: 1732399734118
lifecycle_stage: active
name: /home/elisey/cv/Real-time_Number_Plate_Recognition/data/roboflow_dataset_yolo_v11/logs
